version: 18.12

branches:
  only:
  - master

image: Visual Studio 2017
configuration: Release

platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

cache:
  - packages -> **\packages.config

before_build:
- cmd: >-
    appveyor-retry dotnet restore

build:
  publish_nuget: true
  verbosity: minimal

test_script:

- cmd: dotnet test .\MediaInfo.Wrapper.Tests\MediaInfo.Wrapper.Tests.csproj --no-build

